### ISSUE TITLE
how is this different from language-server-bitbake?

### ISSUE THREAD

**Issue by laoshaw** [Freed-Wu/bitbake-language-server#10]
I used to do 'npm install -g language-server-bitbake', how is this one different, which one is for vim coc.nvim?

**Comment by Freed-Wu** [comment]
Some discussion is here:

https://github.com/yoctoproject/vscode-bitbake/pull/156#issuecomment-1993802664

Both can be used at same time. Some features are different. e.g., Document hover. (You can see README.md's screenshot)

coc-bitbake use language-server-bitbake because it is also for nodejs. You can set bitbake-language-server in coc-settings.json by yourself.
